---
- hosts: all
  gather_facts: no
  tasks:
    - name: Running apt update
       apt:
        update_cache: yes
    - name: Installing required packages
       apt:
         name: git
        state: present
      with_items:
        - git
