---
- hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: false
  tasks:
   - name: 'CheckforPython'
     raw: test -e /usr/bin/python
     changed_when: false
     failed_when: false
     register: check_python

   - name: 'Install_Python'
     raw: apt -y  install python 
     when: check_python.rc != 0

